# Generated by Django 4.0.3 on 2022-05-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_pause',
            new_name='submit',
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
