# Generated by Django 4.0.3 on 2022-05-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_guest_can_pause_room_submit_alter_room_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='school',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
